version: 1
disable_existing_loggers: False
formatters:
    verbose:
        format: '%(asctime)s -- %(levelname)s - %(module)s.%(funcName)s(): %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
    simple:
        format: '%(asctime)s -- %(levelname)s - %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: verbose
        filename: info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: verbose
        filename: errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    mba2mfii:
        level: INFO
        handlers: [console, info_file_handler]
        propagate: False

root:
#    level: INFO
    handlers: [console, info_file_handler, error_file_handler]

